#!/bin/sh

src=$1
target=$2

echo "source" $src
echo "target" $target

inotifywait -mrq --timefmt '%d/%m/%y %H:%M' \
    --format  '%T %w%f'  \
    -e modify,delete,create  \
    --exclude "(#|\.git|\.svn)" ${src} | while read file
do
    cd ${src} && rsync -aztH --delete --progress --rsh='ssh -p32200' ${src} ${target}
    echo "."
done
